# Generated by Django 5.0 on 2023-12-09 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('actor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('actor_first_name', models.CharField(max_length=100)),
                ('actor_last_name', models.CharField(max_length=100)),
                ('actor_species', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_language', models.CharField(max_length=100)),
                ('movie_release_country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.actors')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.movies')),
            ],
            options={
                'unique_together': {('movie_id', 'actor_id')},
            },
        ),
    ]
